#pragma  once
#include "imgui.h"
#include "imgui_impl_sdl.h"
#include "imgui_impl_opengl3.h"
#include "SDL_opengl.h"
#include "SDL.h"
#include <string>
#include <memory>
#include <functional>
#include <iostream>
#include "Texture.hpp"